spring:
  profiles:
    active: dev

  application:
    name: demo12

  mvc:
    favicon:
      enabled: true

  cloud:
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8088
      log:
        switch-pid: true
      zkHost: localhost:2181
      zkRootPath: /sentinel_rule

server:
  port: 9080

feign:
  sentinel:
    enabled: true

  httpclient:
    enabled: true
    readTimeOutMillis: 10000
    connectTimeOutMillis: 10000
    maxConnections: 1024
    maxConnectionsPerRoute: 512
    timeToLive: 600
    connectionTimeout: 5000

    #http请求头配置
    headers:
      User-Agent:
        - 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15'
      Cache-Control: 'no-cache'
      Content-Type:
        - application/json

    #重试配置
    retry:
      enabled: true
      maxAttempts: 3
      period: 500
      maxPeriod: 3000

    #基础认证配置
    basicAuth:
      enabled: false
      username: admin
      password: 123456