spring:
  profiles:
    active: dev

  application:
    name: demo12

  mvc:
    favicon:
      enabled: true

  cloud:
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8080
      log:
        switch-pid: true
      zk:
        zkHost: 192.168.28.154:218
        zkRootPath: /sentinel_rule

server:
  port: 9080

feign:
  sentinel:
    enabled: true

  httpclient:
    enabled: true
    maxConnections: 1024
    maxConnectionsPerRoute: 512
    timeToLive: 600
    connectionTimeout: 5000
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15'